# algo 
algo: "RecurrentPPO"
total_timesteps: 6000000
algo_config:
    tensorboard_log: "../../../logs"
    #
    policy: 'MlpLstmPolicy' 
    normalize_advantage: True
    batch_size: 256
    n_steps: 1024
    gamma: 0.9999
    learning_rate: !!float 7.77e-05
    ent_coef: 0.00429
    clip_range: 0.1
    n_epochs: 10
    gae_lambda: 0.9
    max_grad_norm: 5
    vf_coef: 0.19
    use_sde: True
    sde_sample_freq: 8
    policy_kwargs: "dict(log_std_init=0.0, ortho_init=False,
                       lstm_hidden_size=32,
                       enable_critic_lstm=True,
                       net_arch=dict(pi=[64], vf=[64]))"

# env
env_id: "AsmEnv"
config: 
    observation_fn_id: 'observe_2o'
    n_observs: 2
    #
    harvest_fn_name: "default"
    upow: 1
n_envs: 12

# io
repo: "cboettig/rl-ecology"
save_path: "../saved_agents/results/"

# misc
id: "2obs-UM1-lstm-mt-car"
# id: "short-test"
additional_imports: ["torch"]


