# algo 
algo: "PPO"
total_timesteps: 5000000
algo_config:
    tensorboard_log: "../../../logs"
    policy: 'MlpPolicy'
    use_sde: True
    batch_size: 128
    gamma: 0.995
    gae_lambda: 0.999

# env
env_id: "AsmEnv"
config: 
    observation_fn_id: 'observe_1o'
    n_observs: 1
n_envs: 12

# io
repo: "cboettig/rl-ecology"
save_path: "../saved_agents"

# misc
id: "1o-2"
additional_imports: []