# algo 
algo: "TQC"
total_timesteps: 20000000
algo_config:
    tensorboard_log: "../../logs"
    policy: 'MlpPolicy'
    learning_rate: 0.0001
    learning_starts: 1000
    use_sde: True

# env
env_id: "AsmEnv"
config: {'s': 0.97}
n_envs: 12

# io
repo: "cboettig/rl-ecology"
save_path: "../saved_agents"

# misc
id: "2obs"
additional_imports: []
