# algo 
algo: "TQC"
total_timesteps: 5000000
algo_config:
    tensorboard_log: "../../../logs"
    policy: 'MlpPolicy'
    learning_rate: !!float 7.3e-4
    buffer_size: 200000
    batch_size: 512
    ent_coef: 'auto'
    gamma: 0.98
    tau: 0.02
    train_freq: 64
    gradient_steps: 64
    learning_starts: 20000
    use_sde: True
    policy_kwargs: "dict(log_std_init=-3, net_arch=[256, 128])"

# env
env_id: "AsmEnv"
config: 
    observation_fn_id: 'observe_1o'
    n_observs: 1
    upow: 0.6
n_envs: 12

# io
repo: "cboettig/rl-ecology"
save_path: "../saved_agents"

# misc
id: "1o-upow0.6"
additional_imports: ["torch"]
