# algo 
algo: "TQC"
total_timesteps: 5000000
algo_config:
    tensorboard_log: "../../../logs"
    policy: 'MlpPolicy'
    learning_rate: 0.0001
    learning_starts: 1000
    use_sde: True

# env
env_id: "AsmEnv"
config: 
    observation_fn_id: 'observe_2o'
    n_observs: 2
n_envs: 12

# io
repo: "cboettig/rl-ecology"
save_path: "../saved_agents"

# misc
id: "2o"
additional_imports: []
